#!/bin/bash
# 12aug05abu
# (cd java; ./mkJar [-g])

javac -O  ${1:--g:none}  *.java

jar cf pico.jar \
   Pico.class Pico\$?.class \
   InOut.class \
   Front.class Front\$?.class \
   PicoAdjustmentListener.class PicoFocusListener.class \
   PicoItemListener.class Pico*Adapter*.class \
   PictField*.class JPopUp.class

jar cf gl.jar \
   Z3d*.class

rm *.class
