#!/bin/bash
# 13jun05abu
# (cd java; ./mkJar [-g])

javac -O  ${1:--g:none}  -target 1.1  *.java

jar cf pico.jar \
   Pico.class Pico\$?.class \
   InOut.class \
   Front.class Front\$?.class \
   PicoAdjustmentListener.class PicoFocusListener.class \
   PicoItemListener.class Pico*Adapter*.class \
   Graf.class GLine.class GRect.class GOval.class GText.class \
   GField*.class DrawField*.class PictField*.class \
   Popup.class

jar cf tele.jar \
   Tele*.class

jar cf util.jar \
   Reflector.class InOut.class Util.class

jar cf gl.jar \
   Z3d*.class

rm *.class
