#!/bin/sh
# 08jun11abu

if test -x /usr/bin/picolisp
then
   /usr/bin/pil mkAsm.l "$@"
elif test -x ../bin/picolisp
then
   ../pil mkAsm.l "$@"
else
   ../ersatz/pil mkAsm.l "$@"
fi

# vi:et:ts=3:sw=3
