#!/bin/sh
# 14dec16abu

if test -x /usr/bin/picolisp
then
   /usr/bin/pil mkAsm.l "$@"
elif test -x ../bin/picolisp
then
   ../pil mkAsm.l "$@"
elif which java >/dev/null
then
   ../ersatz/pil mkAsm.l "$@"
else
   echo "No PicoLisp binary found for bootstrapping"
fi

# vi:et:ts=3:sw=3
